server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    include-message: never

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.car_backend: INFO
    org.springframework.security: WARN
    org.hibernate: WARN

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
